{{ if eq .Values.dbSettings.dbProvider "local"}}
apiVersion: v1
kind: Service
metadata:
  name: diffgram-postgres
  namespace: {{ .Release.Namespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-failed
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
{{ end }}

